config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'empleados#home'
  get 'calculadora', to: 'utilitarios#calculadora'
  get 'conversor', to: 'utilitarios#conversor'
  resources :empleados
  get 'nomina', to: 'empleados#nomina'
  get 'api/v1/empleados', to: 'api/v1/empleados#index', defaults: { format: :json }
  get 'api/v1/nomina', to: 'api/v1/nomina#index', defaults: { format: :json }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
    default_scope { order(created_at: :desc) }
    
    validates :cedula, presence: true
    validates :position, presence: true

end

app/models/nomina.rb
class Nomina < ApplicationRecord
    
    validates :age, presence: true
    validates :month, presence: true
    validate :anti_duplicate


    def anti_duplicate
        nominas = Nomina.where('age = ? and month = ?', self.age, self.month)
        if nominas.count > 0
            errors.add(:age, ", Esta nomina ya existe!")
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/empleados_controller.rb
class EmpleadosController < ApplicationController

    before_action :current_employee, only: [:show, :edit, :update, :destroy]

    def home
        
    end

    def index
        @employees = Employee.all
    end

    def show
        @employee = Employee.find(params[:id])
    end

    def new
        @employee = Employee.new
    end
    
    def create
        employee = Employee.create(employee_params)

        redirect_to empleado_path(employee)
    end

    def edit
        @employee = Employee.find(params[:id])
    end

    def update
        @employee = Employee.find(params[:id])
        @employee.update(employee_params)

        redirect_to empleado_path(@employee)
    end

    def destroy
        @employee = Employee.find(params[:id])
        @employee.destroy

        redirect_to empleados_path
    end

    private
        def employee_params
        params.require(:employee).permit(:cedula, :name, :lastname, :phone, :email, :department, :position, :date_entry, :salary)
        end

        def current_employee
            @employee = Employee.find(params[:id])
        end
end

app/controllers/nomina_controller.rb
class NominaController < ApplicationController
    before_action :current_nomina, only: [:edit, :update, :destroy]

    def index
        @nominas = Nomina.all
    end

    def new
        @nomina = Nomina.new
    end
    
    def create
        date = params[:date].split("-")
        age = date[0]
        month = date[1]
        total = Employee.where("date_entry <= ?", params[:date].concat("-01")).sum(:salary)
        
        @nomina = Nomina.new(age: age, month: month, total_amount: total)

        if @nomina.valid?
            @nomina.save
            redirect_to nomina_index_path
        else
            # redirect_to new_nomina_path
            render :new
        end
        

    end

    def edit
        nomina = Nomina.find(params[:id])
        age = @nomina.age
        month = @nomina.month
        @date = age + "-" + month
    end

    def update
        @nomina = Nomina.find(params[:id])
        @nomina.update(nomina_params)

        redirect_to nomina_index_path(@nomina)
    end

    def destroy
        @nomina = Nomina.find(params[:id])
        @nomina.destroy

        redirect_to nomina_index_path(@nomina)
    end

    private

        def current_nomina
            @nomina = Nomina.find(params[:id])
        end
end

app/controllers/utilitarios_controller.rb
class UtilitariosController < ApplicationController

    def calculadora
        @result = 0
        @value = 0

        if !params[:a].nil?
            @value = params[:a]
        end

        if !params[:operation].nil?
            @result = self.send(params[:operation], *[params[:a], params[:b]])
        end
        render :calculadora
    end

    def conversor
        @result = 0
        @value = 0

        if !params[:a].nil?
            @value = params[:a]
        end

        if !params[:operation].nil?
            @result = self.send(params[:operation], *[params[:a]])
        end
        render :conversor
    end

    private
        # Calculadora

        def sum(a = 0, b = 0)
            a.to_f + b.to_f
        end
    
        def subtr(a = 0, b = 0)
            a.to_f - b.to_f
        end

        def multp(a = 0, b = 0)
            a.to_f * b.to_f
        end

        def div(a = 0, b = 0)
            a.to_f / b.to_f
        end

        # Conversor de unidades

        def tofah(a = 0)
            separate_comma((a.to_f * 1.8) + 32).to_s + ' °F'
        end

        def tocel(a = 0)
            separate_comma((a.to_f - 32) * (0.55555555555555555)).to_s + ' °C'
        end

        def todop(a = 0)
            'RD$' + separate_comma(a.to_f * 58.50).to_s
        end

        def tousd(a = 0)
            'USD$' + separate_comma(a.to_f / 58.50).to_s
        end

        def separate_comma(number)
            whole, decimal = number.to_s.split(".")
            whole_with_commas = whole.chars.to_a.reverse.each_slice(3).map(&:join).join(",").reverse
            [whole_with_commas, decimal].compact.join(".")
        end
end

app/helpers/api/v1/empleados_helper.rb
module Api::V1::EmpleadosHelper
end

app/helpers/api/v1/nomina_helper.rb
module Api::V1::NominaHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/empleados_helper.rb
module EmpleadosHelper
end

app/helpers/nomina_helper.rb
module NominaHelper
end

app/helpers/utilitarios_helper.rb
module UtilitariosHelper
end

app/views/empleados/_form.html.erb
<%= form_for @employee, url: empleados_path do |form| %>

    <div class="form-group">
        <label>Cedula</label>
        <%= form.text_field :cedula, placeholder: "Ingrese su cedula", class: 'form-control cedula', :required => true %>
    </div>
    <div class="form-group">
        <label>Nombre</label>
        <%= form.text_field :name, placeholder: "Ingrese su nombre", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Apellido</label>
        <%= form.text_field :lastname, placeholder: "Ingrese su apellido", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Telefono</label>
        <%= form.number_field :phone, placeholder: "Ingrese un telefono", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Email</label>
        <%= form.email_field :email, placeholder: "Ingrese su email", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Departamento</label>
        <%= form.text_field :department, placeholder: "Ingrese un departamento", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Cargo</label>
        <%= form.select(:position, options_for_select([['Developer', 'Developer'], ['UI Designer', 'UI Designer'], ['Project Leader', 'Project Leader']]), {}, {class: "custom-select"}) %>
    </div>
    <div class="form-group">
        <label>Fecha de ingreso</label>
        <%= form.date_field :date_entry, placeholder: "Ingrese su fecha de ingreso", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Salario</label>
        <%= form.number_field :salary, class: 'form-control', :required => true  %>
    </div>

  <%= form.submit class: 'btn btn-primary', value: 'Crear empleado' %>
<% end %>

app/views/empleados/edit.html.erb
<%= form_for @employee, url: empleado_path(@employee), html: {method: "patch"} do |form| %>

    <div class="form-group">
        <label>Cedula</label>
        <%= form.text_field :cedula, placeholder: "Ingrese su cedula", class: 'form-control cedula', :required => true %>
    </div>
    <div class="form-group">
        <label>Nombre</label>
        <%= form.text_field :name, placeholder: "Ingrese su nombre", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Apellido</label>
        <%= form.text_field :lastname, placeholder: "Ingrese su apellido", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Telefono</label>
        <%= form.number_field :phone, placeholder: "Ingrese un telefono", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Email</label>
        <%= form.email_field :email, placeholder: "Ingrese su email", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Departamento</label>
        <%= form.text_field :department, placeholder: "Ingrese un departamento", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Cargo</label>
        <%= form.select(:position, options_for_select([['Developer', 'Developer'], ['UI Designer', 'UI Designer'], ['Project Leader', 'Project Leader']]), {}, {class: "custom-select", :required => true}) %>
    </div>
    <div class="form-group">
        <label>Fecha de ingreso</label>
        <%= form.date_field :date_entry, placeholder: "Ingrese su fecha de ingreso", class: 'form-control', :required => true  %>
    </div>
    <div class="form-group">
        <label>Salario</label>
        <%= form.number_field :salary, class: 'form-control', :required => true  %>
    </div>

  <%= form.submit class: 'btn btn-primary', value: 'Editar empleado' %>
<% end %>

<script>
    $(document).ready(function(){
        $('.cedula').mask('000-0000000-0');
    });
</script>

app/views/empleados/home.html.erb
<div class="alert alert-info" role="alert">
  <h4 class="alert-heading">Bienvenido a Recursos humanos</h4>
  <p>Aqui podras gestionar tus empleados y consultar la nómina.</p>
  <hr>
  <p class="mb-0">También incluye herramientas como calculadora, conversor de temperaturas y conversor de monedas.</p>
</div>

<div class="card-deck">
  <div class="card">
    <%= image_tag("empleado.jpg", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title">Gestionar Empleados</h5>
      <p class="card-text">Añade, edita o elimina empleados.</p>
    </div>
    <div class="card-footer">
      <%= link_to 'Ir a Empleados', empleados_path, class: 'card-link' %>
    </div>
  </div>
  <div class="card">
    <%= image_tag("nomina.jpg", class: "card-img-top nomina") %>
    <div class="card-body">
      <h5 class="card-title">Nómina</h5>
      <p class="card-text">Consulta la nómina por mes-año.</p>
    </div>
    <div class="card-footer">
      <%= link_to 'Ir a Nomina', nomina_index_path, class: 'card-link' %>
    </div>
  </div>
  <div class="card">
    <%= image_tag("numbers.png", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title">Calculadora</h5>
      <p class="card-text">Calculos básicos como sumar, restar, multiplicar y dividir.</p>
    </div>
    <div class="card-footer">
      <%= link_to 'Ir a Calculadora', calculadora_path, class: 'card-link' %>
    </div>
  </div>
  <div class="card">
    <%= image_tag("conversor.jpg", class: "card-img-top") %>
    <div class="card-body">
      <h5 class="card-title">Conversor de unidades</h5>
      <p class="card-text">Convierte unidades de temperaturas Celsius a Fahrenheit y viceversa, también puedes convertir monedas Peso dominicano a Dolares y viceversa.</p>
    </div>
    <div class="card-footer">
      <%= link_to 'Ir a Conversor de unidades', conversor_path, class: 'card-link' %>
    </div>
  </div>
</div>

app/views/empleados/index.html.erb
<div class="row mx-md-n5">
  <div class="col px-md-5"><h2>Empleados</h2></div>
  <div class="col px-md-5"></div>
  <div class="col px-md-5"><%= link_to "Añadir empleado", new_empleado_path, class: 'btn btn-outline-success' %></div>
</div>

<table class="table" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Cedula</th>
      <th scope="col">Nombre</th>
      <th scope="col">Departamento</th>
      <th scope="col">Cargo</th>
      <th scope="col">Salario</th>
      <th scope="col">Accion</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |emp| %>
    <tr>
      <th><%= emp.cedula %></th>
      <td><%= emp.name + ' ' + emp.lastname %></td>
      <td><%= emp.department %></td>
      <td><%= emp.position %></td>
      <td>RD$<%= number_with_precision(emp.salary, :precision => 2, :delimiter => ',') %></td>
      <td>
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group" role="group">
            <%= button_to 'Mostrar', empleado_path(emp), method: 'get', class: 'btn btn-outline-info acciones' %>
          </div>
          <div class="btn-group" role="group">
            <%= button_to 'Editar', edit_empleado_path(emp), method: 'get', class: 'btn btn-outline-warning acciones' %>
          </div>
          <div class="btn-group" role="group">
            <%= button_to 'Eliminar', empleado_path(emp), method: 'delete', data: { confirm: '¿Estas seguro?' }, class: 'btn btn-outline-danger acciones' %>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/empleados/new.html.erb
<%= render 'form' %>


<script>
    $(document).ready(function(){
        $('.cedula').mask('000-0000000-0');
    });
</script>

app/views/empleados/show.html.erb
<div class="card text-center">
  <div class="card-header">
    Empleado
  </div>
  <div class="card-body">
    <h5 class="card-title"><%= @employee.name + ' ' + @employee.lastname %></h5>
    <p class="card-text">Cedula: <%= @employee.cedula %></p>
    <p class="card-text">Telefono: <%= @employee.phone %></p>
    <p class="card-text">Email: <%= @employee.email %></p>
    <p class="card-text">Departamento: <%= @employee.department %></p>
    <p class="card-text">Cargo: <%= @employee.position %></p>
    <p class="card-text">Fecha de ingreso: <%= @employee.date_entry.to_formatted_s(:long) %></p>
    <p class="card-text">Salario: RD$<%= number_with_precision(@employee.salary, :precision => 2, :delimiter => ',') %></p>
    <%= button_to 'Editar', edit_empleado_path(@employee), method: 'get', class: 'btn btn-outline-primary' %>
    <br>
    <%= link_to 'Volver a empleados', empleados_path, class: 'btn btn-outline-secondary' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recursos Humanos</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.10/jquery.mask.js"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm p-3 mb-5" id="homeNavBar">
    <a class="navbar-brand" href="/">Recursos Humanos</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup">
      <div class="nav">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Utilitarios
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Calculadora', calculadora_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Conversor de unidades', conversor_path, class: 'dropdown-item' %>
          </div>
        </li>
        <%= link_to 'Empleados', empleados_path, class: 'nav-item nav-link' %>
        <%= link_to 'Nomina', nomina_index_path, class: 'nav-item nav-link' %>
      </div>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

  <footer id="footer" class="footer" style="padding-top: 60px;">
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <ul class="list-unstyled list-inline social text-center">
            <li class="list-inline-item"><a href="https://www.youtube.com/channel/UC0RfXvPGEcMlJouPg6TL-Hg" target="_blank"><i class="ali ali-yt"></i></a></li>
            <li class="list-inline-item"><a href="https://www.instagram.com/anotherjez/" target="_blank"><i class="ali ali-ig"></i></a></li>
            <li class="list-inline-item"><a href="https://github.com/Anotherjez" target="_blank"><i class="ali ali-git"></i></a></li>
          </ul>
        </div>
      </div>	
      <div class="row">
        <div class="col mx-auto text-center text-white">
          <p><u><a href="/">Sistema de gestion recursos humanos</a></u> es un proyecto con fines educativos</p>
          <p class="h6">© Todos los derechos reservados.<a class="text-green ml-2" href="https://www.instagram.com/anotherjez/" target="_blank">Jesus Mercado</a></p>
        </div>	
      </div>
    </div>
	</footer>
  </body>
</html>

app/views/nomina/edit.html.erb
<h2>Editar nomina</h2>
<br>

<%= form_for @nomina, url: nomina_path(@nomina), html: {method: "patch"} do |form| %>
    <div class="form-group">
        <label>Año y mes</label>
        <input required class="form-control" type="month" id="date" name="date" min="2018-01" value=<%= @date %>>
    </div>
    <div class="form-group">
        <label>Monto total</label>
        <%= form.number_field :total_amount, class: 'form-control', :required => true  %>
    </div>
    
    <%= form.submit class: 'btn btn-primary', value: 'Crear nomina' %>
<% end %>

app/views/nomina/index.html.erb
<div class="row mx-md-n5">
  <div class="col px-md-5"><h2>Nomina</h2></div>
  <div class="col px-md-5"></div>
  <div class="col px-md-5"><%= link_to "Añadir nomina", new_nomina_path, class: 'btn btn-outline-success' %></div>
</div>

<table class="table" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Año</th>
      <th scope="col">Mes</th>
      <th scope="col">Monto total</th>
      <th scope="col">Accion</th>
    </tr>
  </thead>
  <tbody>
    <% @nominas.each do |nom| %>
    <tr>
      <th><%= nom.age %></th>
      <td><%= Time.new(2020, nom.month.to_i, 1).strftime("%B") %></td>
      <td>RD$<%= number_with_precision(nom.total_amount, :precision => 2, :delimiter => ',') %></td>
      <td>
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group" role="group">
            <%= button_to 'Editar', edit_nomina_path(nom), method: 'get', class: 'btn btn-outline-warning acciones' %>
          </div>
          <div class="btn-group" role="group">
            <%= button_to 'Eliminar', nomina_path(nom), method: 'delete', data: { confirm: '¿Estas seguro?' }, class: 'btn btn-outline-danger acciones' %>
          </div>
        </div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/nomina/new.html.erb
<h2>Registrar nomina</h2>
<br>

<%= form_for @nomina, url: nomina_index_path do |form| %>

    <% if @nomina.errors.any? %>
        <% @nomina.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger" role="alert">
                <%= msg %>
            </div>
        <% end %>
    <% end %>

    <div class="form-group">
        <label>Año y mes</label>
        <input required class="form-control" type="month" id="date" name="date" min="2018-01" value=<%= Time.now.strftime("%Y-%m") %>>
    </div>
    
    <%= form.submit class: 'btn btn-primary', value: 'Crear nomina' %>
<% end %>

app/views/utilitarios/calculadora.html.erb
<h2>Calculadora</h2>
<br>
<h4>Seleccione un tipo de operacion:</h4>
<br>

<%= form_for :calculator, url: { action: :calculadora }, method: :get do |f|   %>
    <%= select_tag :operation, options_for_select([['Suma', :sum], ['Resta', :subtr], ['Multiplicacion', :multp], ['Division', :div]], params[:operation]), class: 'custom-select' %>
    <div class="row" style="margin-top: 20px;">
        <div class="col">
            <label>Primer Numero</label>
            <%= number_field_tag :a, params[:a], class: 'form-control', step: 'any', :required => true %>
        </div>
        
        <div class="col">
            <label>Primer Numero</label>
            <%= number_field_tag :b, params[:b], class: 'form-control', step: 'any', :required => true %>
        </div>
    </div>
    <br>
  <center><%= f.submit 'Calcular', class: 'btn btn-primary' %></center>
<% end %>

<% unless @result.nil? %>
  <center><div class="result"><h1>Resultado: <%= number_with_precision(@result, :precision => 4, :delimiter => ',') %></h1></div></center>
<% end %>

app/views/utilitarios/conversor.html.erb
<h2>Conversor de unidades</h2>
<br>
<h4>Seleccione un tipo de operacion:</h4>
<br>

<%= form_for :conversor, url: { action: :conversor }, method: :get do |f|   %>
    <%= react_component("Conversor", prerender: false) %>
    <div class="row" style="margin-top: 20px;">
        <div class="col">
            <label>Valor</label>
            <%= number_field_tag :a, @value, class: 'form-control', step: 'any', :required => true %>
        </div>        
    </div>
    <br>
  <center><%= f.submit 'Calcular', class: 'btn btn-primary' %></center>
<% end %>

<% unless @result.nil? %>
  <center><div class="result"><h1>Resultado: <%= @result %></h1></div></center>
<% end %>